# Generated by Django 5.1.6 on 2025-03-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='investigation_name',
            field=models.CharField(default='Untitled Investigation', help_text='Enter the name or title of the investigation.', max_length=255),
        ),
    ]
